name = "Based Server"
author = "wiryfuture"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa7ba258e3b1b2fa457968240c37ce8cd06ee866546ec7dd16a9776dcd4685d5"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.75"
