name = "Based Server"
author = "wiryfuture"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4625cf26249f57f6d536c58adf8341afa2ee7e0fe3cc86f159dddf88425b3453"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.75"
