name = "Based Server"
author = "wiryfuture"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8636ddbd3d45aa12a6decba83d66f9168aaabee8cde851cd0788ac62ab66494f"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.75"
