name = "Unbelievably Based 1 . 19 . 2 Server"
author = "wiryfuture"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d109733ec958d534555d6e2227ecf32a72acf071fd8ddbccd43a897582d9e5ea"

[versions]
minecraft = "1.19.2"
quilt = "0.17.5-beta.2"
