name = "Based Server"
author = "wiryfuture"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb94cbc6e9e34993be50f3752ae5f4d6ed7346f40ae70cb2586df68404879a05"

[versions]
minecraft = "1.19.3"
quilt = "0.18.1-beta.75"
